# Pull request workflow to check semantic-release compatibility.

on:
  workflow_call: {}

jobs:
  pullrequest-semantic:
    runs-on: ubuntu-latest

    steps:
      # This can happen before checkout because we already have all the metadata
      - name: Check pull request title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commits
        uses: vtavernier/github-workflows/actions/commitlint@463fff6e61c01fc139d544de20af9e80fdd6ee51
        with:
          lint-from: HEAD~${{ github.event.pull_request.commits }}
          lint-to: HEAD
