# docs: skip

name: Release workflow repository

on:
  push:
    branches:
      - master
      - alpha
      - beta
    tags-ignore:
      - "**"

jobs:
  release-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies using yarn
        run: yarn install --frozen-lockfile

      - name: Release workflows
        run: yarn release
